apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

labels:
  - pairs:
      app.kubernetes.io/name: mom
      app.kubernetes.io/component: memory
      app.kubernetes.io/part-of: stevedores
    includeSelectors: true
    includeTemplates: true

resources:
  - serviceaccount.yaml
  - configmap.yaml
  - service.yaml
  - deployment.yaml
