apiVersion: v1
kind: Service
metadata:
  name: mom
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: mom
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
